### ISSUE TITLE
License the logo under Creative Commons?

### ISSUE THREAD

**Issue by lidel** [ipfs/logo#1]
There probably should be a LICENSE file in this repository (with, for example [CC BY-SA 4.0](https://github.com/cc-archive/legalcode/blob/master/by-sa_4.0.txt)), so that community projects such as [ipfs-chrome-extension](https://github.com/dylanPowers/ipfs-chrome-extension) / [ipfs-firefox-addon](https://github.com/lidel/ipfs-firefox-addon) can safely reuse it :gift: 

Or maybe just add it at the end of README.md, for exampe:

``` html
### License

<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/80x15.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.
```

renders as:

> ### License
> 
> <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/80x15.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.

**Comment by jbenet** [comment]
Good point! Wonder if it should just be CC-Attribution. (For ex the golang gopher is). Ideally would use a license that would make it able to be copied and derived, but not used to evoke our support of things without our permission. (In spirit of a BSD license almost)

—

**Comment by lidel** [comment]
CC-Attribution(-SA)  should be fine.

Otherwise it is a slippery-slope and you end up in “freezing logo” to be used only with unaltered codebase, like in case of Firefox: 

> The name "Mozilla Firefox" is a registered trademark; along with the official Firefox logo, it may only be used under certain terms and conditions. Anyone may redistribute the official binaries in unmodified form and use the Firefox name and branding for such distribution, but restrictions are placed on distributions which modify the underlying source code.
> 
> Mozilla has placed the Firefox logo files under [open-source licenses](https://mxr.mozilla.org/mozilla-central/source/browser/branding/official/LICENSE), but its [trademark guidelines](https://www.mozilla.org/en-US/foundation/trademarks/policy/) do not allow displaying altered or similar logos in contexts where trademark law applies.
> – https://en.wikipedia.org/wiki/Firefox#Trademark_and_logo

That is why [Debian renamed Firefox to Iceweasel](https://en.wikipedia.org/wiki/Mozilla_Corporation_software_rebranded_by_the_Debian_project). :confused:

**Comment by Mithgol** [comment]
Remember that the “-SA” (“share-alike”) part of CC-BY-SA means that you cannot distribute a derivative work under a license other than CC-BY-SA (or a compatible license such as CC-BY-SA-ND). See [CC-BY-SA 3.0 Legal Code](https://creativecommons.org/licenses/by-sa/3.0/legalcode), section 4b.

I am not a lawyer, but I think that such licensing makes the use of CC-BY-SA-licensed IPFS logo in CC0-licensed [IPFS addon for Firefox](https://github.com/lidel/ipfs-firefox-addon) questionable.

**Comment by lidel** [comment]
Note that CC0 is not a license _per se_: it is a legal tool for waiving as many rights as legally possible, worldwide (FSF recommends CC0 as the preferred method of releasing software into the public domain).

According to Creative Commons FAQ it is perfectly fine to remix CC-BY-SA with CC0/PD, as long as credit is given where credit is due:
- [Can I combine material that uses different Creative Commons licenses into my work?](https://wiki.creativecommons.org/wiki/Frequently_Asked_Questions#Can_I_combine_material_under_different_Creative_Commons_licenses_in_my_work.3F)

I updated LICENSE section to emphasize that the Logo is licensed separately under CC-BY-SA.

**Comment by jbenet** [comment]
thanks! closing this.
