### ISSUE TITLE
Alpha Channel + Template Image for Electron OS X menubar/tray icon

### ISSUE THREAD

**Issue by bcomnes** [ipfs/logo#5]
https://github.com/ipfs/logo/pull/4 Provides the high rez version of the current icon for the tray, but ultimately we should use a template image:

See: 
- https://github.com/atom/electron/blob/master/docs/api/native-image.md#template-image
- https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/ToolbarIcons.html

**Comment by jbenet** [comment]
SGTM. 

the "wider stroke" version is https://github.com/ipfs/logo/blob/master/ipfs-logo-wider-strokes.pxm which is a Pixelmator file. (ughhh proprietary :(. i've yet to have a good experience with gimp)

**Comment by bcomnes** [comment]
I _really_ would appreciate a screencast of substack working on his drawings.  I have a copy of Pixelmator and will poke around time permitting.

**Comment by jbenet** [comment]
@substack me too!
