### ISSUE TITLE
Vectorized & Outlined Versions

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/logo#6]
Needed for https://github.com/ipfs/electron-app/pull/43

**Comment by dignifiedquire** [comment]
This is by far not pixel perfect, but what I have so far:

![screen shot 2015-09-29 at 18 33 30](https://cloud.githubusercontent.com/assets/790842/10171116/b04cbedc-66d8-11e5-9c84-4164b95aa410.png)

What do you think @jbenet ?

**Comment by whyrusleeping** [comment]
@Dignifiedquire i like it. that looks sleek

**Comment by jbenet** [comment]
@Dignifiedquire if this is just raster, i just added a set of white-outline versions to https://github.com/ipfs/logo 

if this is vector, we should get it mathematically correct.

**Comment by dignifiedquire** [comment]
@jbenet the versions you made look good, but I need one the size of the tray icon, as resizing the 128 version looks pretty bad

**Comment by jbenet** [comment]
https://github.com/ipfs/logo/commit/91b6454c4d20bf66000466c34d2ecd40e37a8250

**Comment by jbenet** [comment]
My opinion has been swayed by @Dignifiedquire, @mappum, and others. What if we cast a wide net for a lot of people to suggest versions of the logo (based on the same idea-- hex/cube so it tessellates and so on -- but giving people a shot at making it look great + more 3D). If several people give it a shot and influence each others ideas we can arrive at something really good.

Eventually, we'll have to trademark to logo to prevent abuse-- for example plastering it on products that ARE NOT actually ipfs compliant (this was important for the linux community to do with the tux logo, for example). so doing a bit of work now and get a really good one will be good.

**Comment by kyledrake** [comment]
@Dignifiedquire This is great. I like the logo. The font is better. Can I start using this?

**Comment by dignifiedquire** [comment]
@kyledrake you're free to use them from my side, it's more @jbenet call if he is okay with that.

**Comment by jbenet** [comment]
i belive those are raster? @kyledrake see  https://github.com/ipfs/logo

i want a proper vector logo, but see my comment, i want to do this really right and try a bunch of people's perspectives on it. we will be trademarking it, so we should spend more effort now on getting something really good.

**Comment by dignifiedquire** [comment]
The version I uploaded is a screenshot of a vector version. Here is the illustrator source for anyone who wants to play with it: http://ipfs.io/ipfs/QmR84FoT13yPgxLHM7tMYXsaR3BNLkf426C2Af8ZZvNb8v
I do not consider it finished (needs cleanup and "pixel perfection" at a minimum) Also we need to create different versions of the vector for different sizes, as the regular scaling does not work for delicate lines like we have on the cube.

**Comment by jbenet** [comment]
thanks!

**Comment by jbenet** [comment]
### Some inspiration for "3Dness"

![](http://www.pd4pic.com/images/box-flat-icon-orange-cube-shape-cubes-shapes.png)
![](http://www.pd4pic.com/images/box-green-flat-icon-free-cube-shape-cubes.png)
![](https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRoDSCvWcGHUbzJDcwu0hCDJrPvKnv8IWPtbDWVYPXr_Oewe1LA)
![](http://blueblots.com/wp-content/uploads/2009/07/icons9.jpg)

**Comment by jbenet** [comment]
(these o/ dont have nice prominent vertices (for representing "nodes in a network") but they do give a good 3D-ness)

**Comment by meyerzinn** [comment]
Any update on this? @dignifiedquire @jbenet @whyrusleeping 

I need something like @dignifiedquire 's logo for the short promo video. Can I get the AI version?

EDIT: Just noticed the source link, thanks!

**Comment by Kubuxu** [comment]
Vector logos were done some time ago: https://github.com/ipfs/logo/tree/master/vector

I will close it.
